first = 'Hello World. This is python string tutorial'
string_methods = ['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold',
                  'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']
print('Starts with "Hello" : {0}'.format(first.startswith('Hello')))
print('Starts with "hello" : {0}'.format(first.startswith('hello')))
print('Ends with "ial" : {0}'.format(first.endswith('ial')))
print('Capitalize "hello": {0}'.format('hello'.capitalize()))
print('Casefold (Lowercase) "HEllo": {0}'.format('hello'.casefold()))
print('Center "hello": {0}'.format('hello'.center(50, '*')))
print('Occurrences of "o" : {0}'.format(first.count('or')))
print('Encode : {0}'.format(first.encode('utf-8', 'xmlcharrefreplace')))
print('Find (finds index) : {0}'.format(first.find('or')))
print('UPPER : {0}'.format(first.upper()))
print('lower : {0}'.format(first.lower()))
print('Replace : {0}'.format(first.replace('or', '*FOR*', -1)))
print('Is Identifier : {0}'.format('def'.isidentifier()))
print('Patition : {0}'.format(first.partition(' ')))
print('RSplit : {0}'.format(first.rsplit(' ', 3)))
print('Split : {0}'.format(first.split(' ', -1)))
print('Index : {0}'.format(first.index('or', 8)))
